import{a as w,S as B,i as n}from"./assets/vendor-BkVuWn-o.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))p(o);new MutationObserver(o=>{for(const s of o)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&p(u)}).observe(document,{childList:!0,subtree:!0});function r(o){const s={};return o.integrity&&(s.integrity=o.integrity),o.referrerPolicy&&(s.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?s.credentials="include":o.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function p(o){if(o.ep)return;o.ep=!0;const s=r(o);fetch(o.href,s)}})();const x="https://pixabay.com/api/",R="54180070-46282e1a529b434bb638d8dc5";async function y(e,t=1){return(await w.get(x,{params:{key:R,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}})).data}const g=document.querySelector(".gallery"),h=document.getElementById("myButton"),L=document.getElementById("search-loader"),q=new B(".gallery a",{captionsData:"alt",captionDelay:250});function b(e){const t=e.map(r=>`
      <li class="gallery-item">
        <a href="${r.largeImageURL}">
          <img class="gallery-image" src="${r.webformatURL}" alt="${r.tags}" />
        </a>
        <div class="info">
          <p class="info-item-text">Likes <span class="info-item-text-span">${r.likes}</span></p>
          <p class="info-item-text">Views <span class="info-item-text-span">${r.views}</span></p>
          <p class="info-item-text">Comments <span class="info-item-text-span">${r.comments}</span></p>
          <p class="info-item-text">Downloads <span class="info-item-text-span">${r.downloads}</span></p>
        </div>
      </li>
    `).join("");g.insertAdjacentHTML("beforeend",t),q.refresh()}function E(){g.innerHTML=""}function I(){h.style.display="block"}function l(){h.style.display="none"}function S(){L.classList.add("active")}function f(){L.classList.remove("active")}const M=document.querySelector(".form"),m=document.getElementById("text"),a=document.getElementById("myButton");let i=1,c="";const v=15;function d(e){e?(a.classList.add("loading"),a.disabled=!0):(a.classList.remove("loading"),a.disabled=!1)}function $(){const e=document.querySelector(".gallery li");if(e){const{height:t}=e.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}}M.addEventListener("submit",async e=>{if(e.preventDefault(),c=m.value.trim(),m.value="",i=1,E(),l(),!c){n.error({message:"Enter search query!",position:"topRight",timeout:3e3});return}try{S();const t=await y(c,i);if(f(),!t.hits||t.hits.length===0){n.error({message:"No images found. Try another query.",position:"topRight",timeout:3e3});return}b(t.hits),i*v>=t.totalHits?(l(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:3e3})):I()}catch(t){f(),n.error({message:"Something went wrong. Try again later.",position:"topRight",timeout:3e3}),console.error(t)}});a.addEventListener("click",async()=>{i+=1,d(!0);try{const e=await y(c,i);if(d(!1),!e.hits||e.hits.length===0){l(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:3e3});return}b(e.hits),$(),i*v>=e.totalHits&&(l(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:3e3}))}catch(e){d(!1),n.error({message:"Something went wrong. Try again later.",position:"topRight",timeout:3e3}),console.error(e)}});
//# sourceMappingURL=index.js.map
